# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Upload to Dropbox CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Add .env file
      run: |
        printf "dropboxToken=${{ secrets.DROPBOX_TOKEN }}\nrepoName=\"JU BCSE Compiler Design\"" > .env
        ([ -f '.env' ] && echo "File write success") || echo "Error writing .env file"
    - name: Run upload command
      run: npm run upload
      
    - name: Copy sharing.md to build folder
      run: |
        mkdir build
        cp sharing.md build/README.md
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
          branch: gh-pages
          folder: build
          clean: false
